let dados = [
  {
    empresa: "Photosnap",
    cargo: "Senior Frontend Developer",
    day: "1d ago",
    escala: "Full time",
    local: "USA only",
  },
  {
    empresa: "Netflix",
    cargo: "Engenheiro de DevOps",
    day: "5d ago",
    escala: "Full time",
    local: "Los Angeles, USA",
  },
  {
    empresa: "Spotify",
    cargo: "Desenvolvedor Mobile (Flutter)",
    day: "1d ago",
    escala: "Full time",
    local: "Estocolmo, Suécia",
  },
  {
    empresa: "Tesla",
    cargo: "Engenheiro de Software Embarcado",
    day: "2w ago",
    escala: "Full time",
    local: "Austin, USA",
  },
  {
    empresa: "Nubank",
    cargo: "Analista de Segurança da Informação",
    day: "3d ago",
    escala: "Full time",
    local: "São Paulo, Brasil",
  },
  {
    empresa: "Microsoft",
    cargo: "Arquiteto de Soluções em Cloud",
    day: "1w ago",
    escala: "Full time",
    local: "Redmond, USA",
  },
  {
    empresa: "Mercado Livre",
    cargo: "Desenvolvedor Front-end (React)",
    day: "4d ago",
    escala: "Full time",
    local: "Buenos Aires, Argentina",
  },
  {
    empresa: "99",
    cargo: "Engenheiro de Dados",
    day: "2w ago",
    escala: "Full time",
    local: "Belo Horizonte, Brasil",
  },
  {
    empresa: "Oracle",
    cargo: "Consultor em Banco de Dados",
    day: "1d ago",
    escala: "Full time",
    local: "Remote",
  },
  {
    empresa: "StartUp Financeira",
    cargo: "Desenvolvedor Blockchain",
    day: "3d ago",
    escala: "Full time",
    local: "Lisboa, Portugal",
  },
  {
    empresa: "Empresa de E-commerce",
    cargo: "Especialista em UX/UI Design",
    day: "1w ago",
    escala: "Full time",
    local: "Berlim, Alemanha",
  },
  {
    empresa: "Hospital São Lucas",
    cargo: "Enfermeiro",
    day: "2d ago",
    escala: "12x36",
    local: "Porto Alegre, Brasil",
  },
  {
    empresa: "Agência de Marketing XYZ",
    cargo: "Designer Gráfico",
    day: "1w ago",
    escala: "Full time",
    local: "São Paulo, Brasil",
  },
  {
    empresa: "Construtora ABC",
    cargo: "Engenheiro Civil",
    day: "3d ago",
    escala: "Full time",
    local: "Rio de Janeiro, Brasil",
  },
  {
    empresa: "Escola Bilíngue",
    cargo: "Professor de Inglês",
    day: "1d ago",
    escala: "Part time",
    local: "Curitiba, Brasil",
  },
  {
    empresa: "Restaurante Gourmet",
    cargo: "Chef de Cozinha",
    day: "4d ago",
    escala: "Full time",
    local: "Florianópolis, Brasil",
  },
  {
    empresa: "Loja de Roupas",
    cargo: "Vendedor",
    day: "1w ago",
    escala: "Part time",
    local: "Salvador, Brasil",
  },
  {
    empresa: "Academia de Ginástica",
    cargo: "Personal Trainer",
    day: "2d ago",
    escala: "Autônomo",
    local: "Belo Horizonte, Brasil",
  },
  {
    empresa: "Empresa de Consultoria",
    cargo: "Consultor Financeiro",
    day: "3d ago",
    escala: "Full time",
    local: "Brasília, Brasil",
  },
  {
    empresa: "Agência de Viagens",
    cargo: "Agente de Viagens",
    day: "1d ago",
    escala: "Full time",
    local: "Fortaleza, Brasil",
  },
  {
    empresa: "Clínica Odontológica",
    cargo: "Assistente Dental",
    day: "4d ago",
    escala: "Part time",
    local: "Recife, Brasil",
  },
];


